# Generated by Django 5.2.7 on 2025-11-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_facebook_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
